name: notes_bucket
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  google_fonts: ^6.2.1
  auto_size_text: ^3.0.0
  lottie: ^3.3.2
  audioplayers: ^6.4.0
  flutter_svg: ^2.1.0
  url_launcher: ^6.2.1
  flutter_secure_storage: ^9.2.4
  dart_mappable: ^4.6.1
  intl: ^0.20.2
  path_provider: ^2.1.5
  riverpod: ^3.0.3
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  shared_preferences: ^2.5.3
  rxdart: ^0.28.0
#  flutter_local_notifications: ^19.4.0
  permission_handler: ^12.0.1
  flutter_staggered_grid_view: ^0.7.0
  drift: ^2.29.0
  drift_flutter: ^0.2.7
  equatable: ^2.0.7
  fpdart: ^1.2.0
  internet_connection_checker_plus: ^2.9.1
  riverpod_generator: ^3.0.3
  skeletonizer: ^2.1.1
  hooks_riverpod: ^3.0.3
  flutter_hooks: ^0.21.3+1
  smooth_page_indicator: ^2.0.1
  pinput: ^6.0.1
  blurrycontainer: ^2.1.0
  package_info_plus: ^9.0.0
  firebase_messaging: ^16.1.0
  firebase_core: ^4.3.0
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  drift_dev: ^2.29.0
  build_runner: ^2.10.4
  dart_mappable_builder: ^4.6.0

flutter:

  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/images/
    - assets/animations/

